// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACuqWzsEkxe8NWSUfh6K_Q0qOjzRD4euM',
    appId: '1:211289249677:web:c09a912595e0e77354cfc4',
    messagingSenderId: '211289249677',
    projectId: 'aspiration-asia-5410e',
    authDomain: 'aspiration-asia-5410e.firebaseapp.com',
    storageBucket: 'aspiration-asia-5410e.appspot.com',
    measurementId: 'G-TZ1PY2QWT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVACxAoTo0qZXWwtXivRpoP7HeF9i1SZk',
    appId: '1:211289249677:android:b75fcb26a97895d954cfc4',
    messagingSenderId: '211289249677',
    projectId: 'aspiration-asia-5410e',
    storageBucket: 'aspiration-asia-5410e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoF1deakYdcTGu97ItOzpYsXi0DEW4ptQ',
    appId: '1:211289249677:ios:0e7027df297740e654cfc4',
    messagingSenderId: '211289249677',
    projectId: 'aspiration-asia-5410e',
    storageBucket: 'aspiration-asia-5410e.appspot.com',
    androidClientId: '211289249677-kqaghcatkcs3fob1v9m6794p2uf2rq9d.apps.googleusercontent.com',
    iosClientId: '211289249677-uisc5ifijm8mokpu54oak25ho0b6v35n.apps.googleusercontent.com',
    iosBundleId: 'com.sombreroinfotech.aspAsia',
  );
}
